on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - uses: actions/checkout@v3
      - id: foo
        uses: azzarb/composite-action@main
        with:
          who-to-greet: 'Azeem the Mandalorian'
          
      - run: |
          chmod +x goodbye.sh
        shell: bash
